In [ ]:
import sys
import pandas as pd
from src.staging import staging_fies, staging_inep
from src.transform_layer_1 import transform_inscritos, transform_ofertas, transform_inep, verificar_colunas_inep
from src.transform_layer_2 import tratar_nans_cine_inscritos, tratar_nans_cine_ofertas
from src.trasnform_layer_3 import processar_modalidades_e_peneira
from src.load import load_inscritos,load_ofertas,auditoria_inscritos_carregados,auditoria_ofertas_carregadas,exportar_para_sqlite
    
comando = 'transform'
etapa = '2'

# --- CAMADA: STAGING ---
if comando == "staging":
    staging_fies()
    staging_inep()

# --- CAMADA: TRANSFORM ---
elif comando == "transform":

    if etapa == "1":
        transform_inep()
    elif etapa == "2":
        transform_inscritos()
    elif etapa == "3":
        transform_ofertas()
    elif etapa == "4":
        verificar_colunas_inep()
    elif etapa == "5":
        tratar_nans_cine_inscritos()
    elif etapa == "6":
        tratar_nans_cine_ofertas()
    elif etapa == "7":
        processar_modalidades_e_peneira()
    elif etapa == "all":
        transform_inep()
        transform_inscritos()
        transform_ofertas()
        verificar_colunas_inep()
        tratar_nans_cine_inscritos()
        tratar_nans_cine_ofertas()
        processar_modalidades_e_peneira()

elif comando == "load":

    load_inscritos()
    load_ofertas()
    auditoria_inscritos_carregados()
    auditoria_ofertas_carregadas()
    exportar_para_sqlite()

==================================================
Iniciando Transformação e Unificação: FIES Inscritos
==================================================
Buscando arquivos em: /home/eq_lucas/Documents/projetos/kdd-pipeline-microdata-fies/data/02_staging/microdata fies
  [*] Lendo e padronizando: fies_2_inscricao_2020_sem_duplicata.csv
  [*] Lendo e padronizando: fies_1_inscricao_2020_sem_duplicata.csv
  [*] Lendo e padronizando: fies_2_inscricao_2019_sem_duplicata.csv
  [*] Lendo e padronizando: fies_2_inscricao_2021_sem_duplicata.csv
  [*] Lendo e padronizando: fies_1_inscricao_2021_sem_duplicata.csv
  [*] Lendo e padronizando: fies_1_inscricao_2019_sem_duplicata.csv

[*] Empilhando todos os semestres num único Dataset...
[*] Ordenando o Dataset por Ano e Semestre...

[*] Iniciando Merge com o Dataset Mestre do INEP (Áreas CINE)...
  -> Merge concluído com sucesso! Colunas do INEP adicionadas.
[*] Padronizando tipos numéricos para o Parquet...

--- Processo Concluído! ---
Total de 6 arquivos unificados e enriquecidos.
Checkpoint salvo em: /home/eq_lucas/Documents/projetos/kdd-pipeline-microdata-fies/data/03_transform/fies/fies_inscritos_unificado.parquet
Total de linhas no dataset final: 2197234

==================================================
 INICIANDO VALIDAÇÃO DE QUALIDADE: INSCRITOS
==================================================

⏳ Carregando dados da camada 01_RAW...

----------------------------------------
📊 Análise da Etapa: 01_RAW (Bruto Original)
----------------------------------------
Total de linhas reais do dataset : 2217921
Total de chaves primárias únicas : 2197234

⚠️ ERRO PROVÁVEL: DUPLICAÇÃO DE LINHA ENCONTRADA!
Total de linhas 100% duplicadas: 20687

[ VISUALIZAÇÃO DO DATASET - 01_RAW (Bruto Original) ]

,Ano do processo seletivo,Semestre do processo seletivo,Cod. do Grupo de preferência,Classificação,ID do estudante,Sexo,Data de Nascimento,UF de residência,Municipio de residência,Etnia/Cor,Pessoa com deficiência?,Concluiu ensino médio escola pública,Ano conclusão ensino médio,Concluiu curso superior?,Beneficiado pelo Creduc ou Fies,Professor rede pública ensino?,Nº de membros Grupo Familiar,Renda familiar mensal bruta,Renda mensal bruta per capita,Região grupo de preferência,UF,Cod.Microrregião,Microrregião,Cod.Mesorregião,Mesorregião,Conceito de curso do GP,Área do conhecimento,Subárea do conhecimento,Nota Corte Grupo Preferência,Opções de cursos da inscrição,Nome mantenedora,Natureza Jurídica Mantenedora,CNPJ da mantenedora,Código e-MEC da Mantenedora,Nome da IES,Código e-MEC da IES,Organização Acadêmica da IES,Município da IES,UF da IES,Nome do Local de oferta,Código do Local de Oferta,Munícipio do Local de Oferta,UF do Local de Oferta,Código do curso,Nome do curso,Turno,Grau,Conceito,Média nota Enem,Ano do Enem,Redação,Matemática e suas Tecnologias,"Linguagens, Códigos e suas Tec",Ciências Natureza e suas Tec,Ciências Humanas e suas Tec,Situação Inscrição Fies,Percentual de financiamento,Semestre do financiamento,Qtde semestre financiado
0,2019,1,46540,1,97492018,F,23/09/1997,SC,SÃO MIGUEL DO OESTE,BRANCA,NÃO,NÃO,2014,NÃO,Não,NÃO,2,6495.0,2165.0,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,CURSOS NAO PRIORITARIOS,"CIÊNCIAS BIOLÓGICAS (BEL), BIOMEDICINA, BIOTEC...",635.7,2,ASSOCIACAO PARANAENSE DE CULTURA - APC,PESSOA JURÍDICA DE DIREITO PRIVADO - SEM FINS ...,7.670000e+13,10,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,10,UNIVERSIDADE,CURITIBA,PR,PUCPR - CAMPUS CURITIBA,657676,CURITIBA,PR,861,CIÊNCIAS BIOLÓGICAS,MATUTINO,SEMESTRAL,4,714.42,2018.0,920.0,738.0,620.1,621.8,672.2,NÃO CONTRATADO,NaN,,NaN
1,2019,1,46540,1,97492018,F,23/09/1997,SC,SÃO MIGUEL DO OESTE,BRANCA,NÃO,NÃO,2014,NÃO,Não,NÃO,2,6495.0,2165.0,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,CURSOS NAO PRIORITARIOS,"CIÊNCIAS BIOLÓGICAS (BEL), BIOMEDICINA, BIOTEC...",635.7,3,COMPLEXO DE ENSINO SUPERIOR DO BRASIL LTDA.,PRIVADA COM FINS LUCRATIVOS,2.740000e+12,963,CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL,3602,CENTRO UNIVERSITÁRIO,CURITIBA,PR,UNIDADE SEDE,659556,CURITIBA,PR,94925,BIOMEDICINA,MATUTINO,SEMESTRAL,4,714.42,2018.0,920.0,738.0,620.1,621.8,672.2,NÃO CONTRATADO,NaN,,NaN
2,2019,1,46540,1,97492018,F,23/09/1997,SC,SÃO MIGUEL DO OESTE,BRANCA,NÃO,NÃO,2014,NÃO,Não,NÃO,2,6495.0,2165.0,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,CURSOS NAO PRIORITARIOS,"CIÊNCIAS BIOLÓGICAS (BEL), BIOMEDICINA, BIOTEC...",635.7,1,ASSOCIACAO HOSPITALAR DE PROT INFANCIA DR RAUL...,PRIVADA SEM FINS LUCRATIVOS,7.660000e+13,1812,FACULDADES PEQUENO PRÍNCIPE,2787,FACULDADE,CURITIBA,PR,CAMPUS AVENIDA IGUAÇU,1095611,CURITIBA,PR,91175,BIOMEDICINA,VESPERTINO,SEMESTRAL,4,714.42,2018.0,920.0,738.0,620.1,621.8,672.2,NÃO CONTRATADO,NaN,,NaN
3,2019,1,46540,2,12625187,F,13/01/1990,PR,CURITIBA,BRANCA,NÃO,NÃO,2008,NÃO,Não,NÃO,2,8901.0,2967.0,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,CURSOS NAO PRIORITARIOS,"CIÊNCIAS BIOLÓGICAS (BEL), BIOMEDICINA, BIOTEC...",635.7,2,ASSOCIACAO PARANAENSE DE CULTURA - APC,PESSOA JURÍDICA DE DIREITO PRIVADO - SEM FINS ...,7.670000e+13,10,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,10,UNIVERSIDADE,CURITIBA,PR,PUCPR - CAMPUS CURITIBA,657676,CURITIBA,PR,861,CIÊNCIAS BIOLÓGICAS,MATUTINO,SEMESTRAL,4,707.26,2018.0,920.0,725.3,589.9,609.8,691.3,NÃO CONTRATADO,NaN,,NaN
4,2019,1,46540,2,12625187,F,13/01/1990,PR,CURITIBA,BRANCA,NÃO,NÃO,2008,NÃO,Não,NÃO,2,8901.0,2967.0,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,CURSOS NAO PRIORITARIOS,"CIÊNCIAS BIOLÓGICAS (BEL), BIOMEDICINA, BIOTEC...",635.7,1,ASSOCIACAO HOSPITALAR DE PROT INFANCIA DR RAUL...,PRIVADA SEM FINS LUCRATIVOS,7.660000e+13,1812,FACULDADES PEQUENO PRÍNCIPE,2787,FACULDADE,CURITIBA,PR,CAMPUS AVENIDA IGUAÇU,1095611,CURITIBA,PR,91175,BIOMEDICINA,VESPERTINO,SEMESTRAL,4,707.26,2018.0,920.0,725.3,589.9,609.8,691.3,NÃO CONTRATADO,NaN,,NaN

[ ESTATÍSTICAS DESCRITIVAS - 01_RAW (Bruto Original) ]

,Ano do processo seletivo,Semestre do processo seletivo,Cod. do Grupo de preferência,Classificação,ID do estudante,Ano conclusão ensino médio,Nº de membros Grupo Familiar,Renda familiar mensal bruta,Renda mensal bruta per capita,Cod.Microrregião,Cod.Mesorregião,Nota Corte Grupo Preferência,Opções de cursos da inscrição,CNPJ da mantenedora,Código e-MEC da Mantenedora,Código e-MEC da IES,Código do Local de Oferta,Código do curso,Média nota Enem,Redação,Matemática e suas Tecnologias,"Linguagens, Códigos e suas Tec",Ciências Natureza e suas Tec,Ciências Humanas e suas Tec,Percentual de financiamento,Qtde semestre financiado
count,2.217921e+06,2.217921e+06,2.217921e+06,2.217921e+06,2.217921e+06,2.217921e+06,2.217921e+06,1.947981e+06,2.217921e+06,2.217921e+06,2.217921e+06,2.217917e+06,2.217921e+06,2.217921e+06,2.217921e+06,2.217921e+06,2.217921e+06,2.217921e+06,2.217920e+06,2.217920e+06,2.217920e+06,2.217920e+06,2.217920e+06,2.217920e+06,160404.000000,317779.000000
mean,2.019786e+03,1.325632e+00,7.026355e+04,1.788826e+02,1.712072e+08,2.014551e+03,1.921765e+00,2.973841e+03,1.022211e+03,3.037387e+04,3.040586e+03,5.928816e+02,1.689534e+00,2.058284e+13,3.082828e+03,3.167767e+03,6.631807e+05,7.734225e+05,5.488319e+02,6.217731e+02,5.314809e+02,5.341008e+02,5.015637e+02,5.552410e+02,76.086131,8.721017
std,7.842054e-01,4.686104e-01,3.052079e+04,2.884649e+02,8.712671e+07,5.292533e+00,1.292647e+00,2.325107e+03,6.452939e+02,1.001370e+04,1.001869e+03,7.879045e+01,7.761125e-01,2.327548e+13,5.076316e+03,4.926557e+03,3.719329e+05,9.605055e+05,6.934559e+01,1.494704e+02,1.009619e+02,5.670291e+01,7.282170e+01,7.327723e+01,14.861767,1.966426
min,2.019000e+03,1.000000e+00,4.258300e+04,1.000000e+00,1.251817e+07,1.961000e+03,0.000000e+00,0.000000e+00,0.000000e+00,1.100100e+04,1.101000e+03,4.500000e+02,1.000000e+00,5.985700e+10,1.000000e+01,1.000000e+01,2.240000e+02,8.490000e+02,4.362800e+02,1.200000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,50.000000,0.000000
25%,2.019000e+03,1.000000e+00,4.611900e+04,2.100000e+01,9.753596e+07,2.013000e+03,1.000000e+00,1.448000e+03,5.500000e+02,2.303200e+04,2.307000e+03,5.473800e+02,1.000000e+00,3.950000e+12,3.630000e+02,4.660000e+02,6.578480e+05,6.662700e+04,4.976000e+02,5.200000e+02,4.555000e+02,4.977000e+02,4.471000e+02,5.055000e+02,65.400000,8.000000
50%,2.020000e+03,1.000000e+00,5.716000e+04,6.900000e+01,2.020230e+08,2.016000e+03,2.000000e+00,2.234310e+03,9.000000e+02,3.103000e+04,3.107000e+03,5.805400e+02,1.000000e+00,7.710000e+12,1.119000e+03,1.502000e+03,6.590960e+05,1.209180e+05,5.335800e+02,6.000000e+02,5.177000e+02,5.346000e+02,4.946000e+02,5.583000e+02,80.690000,10.000000
75%,2.020000e+03,2.000000e+00,9.142900e+04,2.070000e+02,2.039443e+08,2.018000e+03,3.000000e+00,3.545000e+03,1.285000e+03,3.506100e+04,3.515000e+03,6.205000e+02,2.000000e+00,3.410000e+13,2.415000e+03,3.029000e+03,1.045224e+06,1.303403e+06,5.824600e+02,7.200000e+02,5.934000e+02,5.714000e+02,5.477000e+02,6.073000e+02,88.410000,10.000000
max,2.021000e+03,2.000000e+00,1.268090e+05,3.014000e+03,3.534557e+08,2.021000e+03,2.900000e+01,5.464642e+04,1.821547e+04,5.300100e+04,5.301000e+03,8.115200e+02,3.000000e+00,9.800000e+13,1.805500e+04,2.455000e+04,2.500004e+06,5.001566e+06,8.190200e+02,1.000000e+03,9.920000e+02,8.098000e+02,8.713000e+02,9.062000e+02,98.690000,16.000000

⏳ Carregando dados da camada 02_STAGING...

----------------------------------------
📊 Análise da Etapa: 02_STAGING (Sem Duplicatas)
----------------------------------------
Total de linhas reais do dataset : 2197234
Total de chaves primárias únicas : 2197234
✅ Nenhuma duplicação de PK encontrada. Integridade perfeita.

[ VISUALIZAÇÃO DO DATASET - 02_STAGING (Sem Duplicatas) ]

,Ano do processo seletivo,Semestre do processo seletivo,Cod. do Grupo de preferência,Classificação,ID do estudante,Sexo,Data de Nascimento,UF de residência,Municipio de residência,Etnia/Cor,Pessoa com deficiência?,Concluiu ensino médio escola pública,Ano conclusão ensino médio,Concluiu curso superior?,Beneficiado pelo Creduc ou Fies,Professor rede pública ensino?,Nº de membros Grupo Familiar,Renda familiar mensal bruta,Renda mensal bruta per capita,Região grupo de preferência,UF,Cod.Microrregião,Microrregião,Cod.Mesorregião,Mesorregião,Conceito de curso do GP,Área do conhecimento,Subárea do conhecimento,Nota Corte Grupo Preferência,Opções de cursos da inscrição,Nome mantenedora,Natureza Jurídica Mantenedora,CNPJ da mantenedora,Código e-MEC da Mantenedora,Nome da IES,Código e-MEC da IES,Organização Acadêmica da IES,Município da IES,UF da IES,Nome do Local de oferta,Código do Local de Oferta,Munícipio do Local de Oferta,UF do Local de Oferta,Código do curso,Nome do curso,Turno,Grau,Conceito,Média nota Enem,Ano do Enem,Redação,Matemática e suas Tecnologias,"Linguagens, Códigos e suas Tec",Ciências Natureza e suas Tec,Ciências Humanas e suas Tec,Situação Inscrição Fies,Percentual de financiamento,Semestre do financiamento,Qtde semestre financiado
0,2020,2,92056,2,203813852,F,15/12/2002,PR,CURITIBA,BRANCA,NÃO,NÃO,2019,NÃO,NÃO,NÃO,3,2400.00,600.00,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,"CURSOS DA ÁREA DE LICENCIATURA, PEDAGOGIA E NO...","ARTES, CIÊNCIAS SOCIAIS E CURSOS RELACIONADOS",521.68,1,ASSOCIACAO PARANAENSE DE CULTURA - APC,PESSOA JURÍDICA DE DIREITO PRIVADO - SEM FINS ...,7.670000e+13,10,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,10,UNIVERSIDADE,CURITIBA,PR,PUCPR - CAMPUS CURITIBA,657676,CURITIBA,PR,849,FILOSOFIA,NOTURNO,SEMESTRAL,4,521.68,2019.0,540.0,421.3,563.0,497.0,587.1,NÃO CONTRATADO,NaN,NaN,NaN
1,2020,2,92061,1,203815683,F,26/06/1974,PR,PINHAIS,BRANCA,NÃO,SIM,1994,NÃO,NÃO,NÃO,2,1784.57,594.86,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,"CURSOS DA ÁREA DE LICENCIATURA, PEDAGOGIA E NO...",PEDAGOGIA,645.34,1,ASSOCIACAO PARANAENSE DE CULTURA - APC,PESSOA JURÍDICA DE DIREITO PRIVADO - SEM FINS ...,7.670000e+13,10,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,10,UNIVERSIDADE,CURITIBA,PR,PUCPR - CAMPUS CURITIBA,657676,CURITIBA,PR,850,PEDAGOGIA,NOTURNO,SEMESTRAL,4,645.34,2010.0,700.0,628.5,642.4,532.2,723.6,NÃO CONTRATADO,NaN,NaN,NaN
2,2020,2,92061,1,203815683,F,26/06/1974,PR,PINHAIS,BRANCA,NÃO,SIM,1994,NÃO,NÃO,NÃO,2,1784.57,594.86,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,"CURSOS DA ÁREA DE LICENCIATURA, PEDAGOGIA E NO...",PEDAGOGIA,645.34,2,ASSOCIACAO PARANAENSE DE CULTURA - APC,PESSOA JURÍDICA DE DIREITO PRIVADO - SEM FINS ...,7.670000e+13,10,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,10,UNIVERSIDADE,CURITIBA,PR,PUCPR - CAMPUS CURITIBA,657676,CURITIBA,PR,850,PEDAGOGIA,MATUTINO,SEMESTRAL,4,645.34,2010.0,700.0,628.5,642.4,532.2,723.6,NÃO CONTRATADO,NaN,NaN,NaN
3,2020,2,92061,7,203816286,F,23/09/1981,PR,CURITIBA,BRANCA,NÃO,SIM,2020,NÃO,NÃO,NÃO,3,3050.00,762.50,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,"CURSOS DA ÁREA DE LICENCIATURA, PEDAGOGIA E NO...",PEDAGOGIA,645.34,2,ASSOCIACAO PARANAENSE DE CULTURA - APC,PESSOA JURÍDICA DE DIREITO PRIVADO - SEM FINS ...,7.670000e+13,10,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,10,UNIVERSIDADE,CURITIBA,PR,PUCPR - CAMPUS CURITIBA,657676,CURITIBA,PR,850,PEDAGOGIA,NOTURNO,SEMESTRAL,4,523.46,2018.0,560.0,456.9,579.9,431.8,588.7,NÃO CONTRATADO,NaN,NaN,NaN
4,2020,2,92061,5,203818907,F,18/05/1999,PR,SÃO MATEUS DO SUL,BRANCA,NÃO,SIM,2016,NÃO,NÃO,NÃO,3,1200.00,300.00,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,"CURSOS DA ÁREA DE LICENCIATURA, PEDAGOGIA E NO...",PEDAGOGIA,645.34,2,ASSOCIACAO PARANAENSE DE CULTURA - APC,PESSOA JURÍDICA DE DIREITO PRIVADO - SEM FINS ...,7.670000e+13,10,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,10,UNIVERSIDADE,CURITIBA,PR,PUCPR - CAMPUS CURITIBA,657676,CURITIBA,PR,850,PEDAGOGIA,NOTURNO,SEMESTRAL,4,534.44,2017.0,580.0,492.1,468.6,565.8,565.7,NÃO CONTRATADO,NaN,NaN,NaN

[ ESTATÍSTICAS DESCRITIVAS - 02_STAGING (Sem Duplicatas) ]

,Ano do processo seletivo,Semestre do processo seletivo,Cod. do Grupo de preferência,Classificação,ID do estudante,Ano conclusão ensino médio,Nº de membros Grupo Familiar,Renda familiar mensal bruta,Renda mensal bruta per capita,Cod.Microrregião,Cod.Mesorregião,Nota Corte Grupo Preferência,Opções de cursos da inscrição,CNPJ da mantenedora,Código e-MEC da Mantenedora,Código e-MEC da IES,Código do Local de Oferta,Código do curso,Média nota Enem,Ano do Enem,Redação,Matemática e suas Tecnologias,"Linguagens, Códigos e suas Tec",Ciências Natureza e suas Tec,Ciências Humanas e suas Tec,Percentual de financiamento,Semestre do financiamento,Qtde semestre financiado
count,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,1.930434e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197230e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197233e+06,2.197227e+06,2.197233e+06,2.197233e+06,2.197233e+06,2.197233e+06,2.197233e+06,160362.000000,0.0,317462.000000
mean,2.019778e+03,1.323185e+00,6.989356e+04,1.800095e+02,1.704581e+08,2.014552e+03,1.923182e+00,2.976886e+03,1.022700e+03,3.038256e+04,3.041455e+03,5.932746e+02,1.688698e+00,2.057784e+13,3.081179e+03,3.167320e+03,6.631268e+05,7.737493e+05,5.489478e+02,2.017279e+03,6.218451e+02,5.316478e+02,5.341709e+02,5.016815e+02,5.553938e+02,76.085875,NaN,8.721104
std,7.809612e-01,4.676926e-01,3.033542e+04,2.894536e+02,8.684756e+07,5.289237e+00,1.292683e+00,2.328033e+03,6.459289e+02,1.001842e+04,1.002339e+03,7.886352e+01,7.759046e-01,2.327840e+13,5.075087e+03,4.925744e+03,3.719027e+05,9.615114e+05,6.944929e+01,2.110164e+00,1.496446e+02,1.010469e+02,5.673541e+01,7.288468e+01,7.330013e+01,14.862076,NaN,1.966325
min,2.019000e+03,1.000000e+00,4.258300e+04,1.000000e+00,1.251817e+07,1.961000e+03,0.000000e+00,0.000000e+00,0.000000e+00,1.100100e+04,1.101000e+03,4.500000e+02,1.000000e+00,5.985700e+10,1.000000e+01,1.000000e+01,2.240000e+02,8.490000e+02,4.362800e+02,2.010000e+03,1.200000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,50.000000,NaN,0.000000
25%,2.019000e+03,1.000000e+00,4.609600e+04,2.200000e+01,9.753182e+07,2.013000e+03,1.000000e+00,1.449000e+03,5.500000e+02,2.303200e+04,2.307000e+03,5.478200e+02,1.000000e+00,3.950000e+12,3.620000e+02,4.660000e+02,6.578480e+05,6.662700e+04,4.975800e+02,2.016000e+03,5.200000e+02,4.555000e+02,4.977000e+02,4.472000e+02,5.056000e+02,65.400000,NaN,8.000000
50%,2.020000e+03,1.000000e+00,5.708700e+04,7.000000e+01,2.019994e+08,2.016000e+03,2.000000e+00,2.238000e+03,9.000000e+02,3.103000e+04,3.107000e+03,5.808400e+02,1.000000e+00,7.710000e+12,1.117000e+03,1.502000e+03,6.590960e+05,1.209160e+05,5.336400e+02,2.018000e+03,6.000000e+02,5.178000e+02,5.346000e+02,4.947000e+02,5.585000e+02,80.690000,NaN,10.000000
75%,2.020000e+03,2.000000e+00,9.114000e+04,2.080000e+02,2.039352e+08,2.018000e+03,3.000000e+00,3.549568e+03,1.286750e+03,3.506100e+04,3.515000e+03,6.206200e+02,2.000000e+00,3.410000e+13,2.415000e+03,3.029000e+03,1.045224e+06,1.303403e+06,5.827000e+02,2.019000e+03,7.200000e+02,5.937000e+02,5.715000e+02,5.479000e+02,6.075000e+02,88.410000,NaN,10.000000
max,2.021000e+03,2.000000e+00,1.268090e+05,3.014000e+03,3.534557e+08,2.021000e+03,2.900000e+01,5.464642e+04,1.821547e+04,5.300100e+04,5.301000e+03,8.115200e+02,3.000000e+00,9.800000e+13,1.805500e+04,2.455000e+04,2.500004e+06,5.001566e+06,8.190200e+02,2.020000e+03,1.000000e+03,9.920000e+02,8.098000e+02,8.713000e+02,9.062000e+02,98.690000,NaN,16.000000

⏳ Carregando dados da camada 03_TRANSFORM...

----------------------------------------
📊 Análise da Etapa: 03_TRANSFORM (Parquet Unificado)
----------------------------------------
Total de linhas reais do dataset : 2197234
Total de chaves primárias únicas : 2197234
✅ Nenhuma duplicação de PK encontrada. Integridade perfeita.

[ VISUALIZAÇÃO DO DATASET - 03_TRANSFORM (Parquet Unificado) ]

,ano_processo_seletivo_inscricao,semestre_processo_seletivo_inscricao,codigo_grupo_preferencia_inscricao,classificacao_inscricao,id_estudante_inscricao,sexo_inscricao,data_nascimento_inscricao,uf_residencia_inscricao,municipio_residencia_inscricao,etnia_cor_inscricao,pessoa_com_deficiencia_inscricao,concluiu_ensino_medio_escola_publica_inscricao,ano_conclusao_ensino_medio_inscricao,concluiu_curso_superior_inscricao,beneficiado_creduc_ou_fies_inscricao,professor_rede_publica_ensino_inscricao,numero_membros_grupo_familiar_inscricao,renda_familiar_mensal_bruta_inscricao,renda_mensal_bruta_per_capita_inscricao,regiao_grupo_preferencia_inscricao,uf_grupo_preferencia_inscricao,codigo_microrregiao_inscricao,microrregiao_inscricao,codigo_mesorregiao_inscricao,mesorregiao_inscricao,conceito_curso_gp_inscricao,area_conhecimento_inscricao,subarea_conhecimento_inscricao,nota_corte_grupo_preferencia_inscricao,opcoes_cursos_inscricao_inscricao,nome_mantenedora_inscricao,natureza_juridica_mantenedora_inscricao,cnpj_mantenedora_inscricao,codigo_e_mec_mantenedora_inscricao,nome_ies_inscricao,codigo_e_mec_ies_inscricao,organizacao_academica_ies_inscricao,municipio_ies_inscricao,uf_ies_inscricao,nome_local_oferta_inscricao,codigo_local_oferta_inscricao,municipio_local_oferta_inscricao,uf_local_oferta_inscricao,codigo_curso_inscricao,nome_curso_inscricao,turno_inscricao,grau_inscricao,conceito_curso_inscricao,media_nota_enem_inscricao,ano_enem_inscricao,nota_redacao_inscricao,nota_matematica_inscricao,nota_linguagens_inscricao,nota_ciencias_natureza_inscricao,nota_ciencias_humanas_inscricao,situacao_inscricao_fies_inscricao,percentual_financiamento_inscricao,semestre_financiamento_inscricao,qtde_semestre_financiado_inscricao,NO_CURSO,CO_CURSO,CO_CINE_AREA_GERAL,NO_CINE_AREA_GERAL
0,2019,1,46540,1,97492018,F,23/09/1997,SC,SÃO MIGUEL DO OESTE,BRANCA,NÃO,NÃO,2014,NÃO,NÃO,NÃO,2,6495.0,2165.0,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,CURSOS NAO PRIORITARIOS,"CIÊNCIAS BIOLÓGICAS (BEL), BIOMEDICINA, BIOTEC...",635.7,2,ASSOCIACAO PARANAENSE DE CULTURA - APC,PESSOA JURÍDICA DE DIREITO PRIVADO - SEM FINS ...,7.670000e+13,10,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,10,UNIVERSIDADE,CURITIBA,PR,PUCPR - CAMPUS CURITIBA,657676,CURITIBA,PR,861,CIÊNCIAS BIOLÓGICAS,MATUTINO,SEMESTRAL,4,714.42,2018,920.0,738.0,620.1,621.8,672.2,NÃO CONTRATADO,NaN,NaN,NaN,Ciências Biológicas,861.0,5.0,"Ciências naturais, matemática e estatística"
1,2019,1,46540,1,97492018,F,23/09/1997,SC,SÃO MIGUEL DO OESTE,BRANCA,NÃO,NÃO,2014,NÃO,NÃO,NÃO,2,6495.0,2165.0,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,CURSOS NAO PRIORITARIOS,"CIÊNCIAS BIOLÓGICAS (BEL), BIOMEDICINA, BIOTEC...",635.7,3,COMPLEXO DE ENSINO SUPERIOR DO BRASIL LTDA.,PRIVADA COM FINS LUCRATIVOS,2.740000e+12,963,CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL,3602,CENTRO UNIVERSITÁRIO,CURITIBA,PR,UNIDADE SEDE,659556,CURITIBA,PR,94925,BIOMEDICINA,MATUTINO,SEMESTRAL,4,714.42,2018,920.0,738.0,620.1,621.8,672.2,NÃO CONTRATADO,NaN,NaN,NaN,Biomedicina,94925.0,9.0,Saúde e bem-estar
2,2019,1,46540,1,97492018,F,23/09/1997,SC,SÃO MIGUEL DO OESTE,BRANCA,NÃO,NÃO,2014,NÃO,NÃO,NÃO,2,6495.0,2165.0,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,CURSOS NAO PRIORITARIOS,"CIÊNCIAS BIOLÓGICAS (BEL), BIOMEDICINA, BIOTEC...",635.7,1,ASSOCIACAO HOSPITALAR DE PROT INFANCIA DR RAUL...,PRIVADA SEM FINS LUCRATIVOS,7.660000e+13,1812,FACULDADES PEQUENO PRÍNCIPE,2787,FACULDADE,CURITIBA,PR,CAMPUS AVENIDA IGUAÇU,1095611,CURITIBA,PR,91175,BIOMEDICINA,VESPERTINO,SEMESTRAL,4,714.42,2018,920.0,738.0,620.1,621.8,672.2,NÃO CONTRATADO,NaN,NaN,NaN,Biomedicina,91175.0,9.0,Saúde e bem-estar
3,2019,1,46540,2,12625187,F,13/01/1990,PR,CURITIBA,BRANCA,NÃO,NÃO,2008,NÃO,NÃO,NÃO,2,8901.0,2967.0,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,CURSOS NAO PRIORITARIOS,"CIÊNCIAS BIOLÓGICAS (BEL), BIOMEDICINA, BIOTEC...",635.7,2,ASSOCIACAO PARANAENSE DE CULTURA - APC,PESSOA JURÍDICA DE DIREITO PRIVADO - SEM FINS ...,7.670000e+13,10,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ,10,UNIVERSIDADE,CURITIBA,PR,PUCPR - CAMPUS CURITIBA,657676,CURITIBA,PR,861,CIÊNCIAS BIOLÓGICAS,MATUTINO,SEMESTRAL,4,707.26,2018,920.0,725.3,589.9,609.8,691.3,NÃO CONTRATADO,NaN,NaN,NaN,Ciências Biológicas,861.0,5.0,"Ciências naturais, matemática e estatística"
4,2019,1,46540,2,12625187,F,13/01/1990,PR,CURITIBA,BRANCA,NÃO,NÃO,2008,NÃO,NÃO,NÃO,2,8901.0,2967.0,SUL,PARANÁ,41037,CURITIBA,4110,METROPOLITANA DE CURITIBA,4,CURSOS NAO PRIORITARIOS,"CIÊNCIAS BIOLÓGICAS (BEL), BIOMEDICINA, BIOTEC...",635.7,1,ASSOCIACAO HOSPITALAR DE PROT INFANCIA DR RAUL...,PRIVADA SEM FINS LUCRATIVOS,7.660000e+13,1812,FACULDADES PEQUENO PRÍNCIPE,2787,FACULDADE,CURITIBA,PR,CAMPUS AVENIDA IGUAÇU,1095611,CURITIBA,PR,91175,BIOMEDICINA,VESPERTINO,SEMESTRAL,4,707.26,2018,920.0,725.3,589.9,609.8,691.3,NÃO CONTRATADO,NaN,NaN,NaN,Biomedicina,91175.0,9.0,Saúde e bem-estar

[ ESTATÍSTICAS DESCRITIVAS - 03_TRANSFORM (Parquet Unificado) ]

,ano_processo_seletivo_inscricao,semestre_processo_seletivo_inscricao,codigo_grupo_preferencia_inscricao,classificacao_inscricao,id_estudante_inscricao,ano_conclusao_ensino_medio_inscricao,numero_membros_grupo_familiar_inscricao,renda_familiar_mensal_bruta_inscricao,renda_mensal_bruta_per_capita_inscricao,codigo_microrregiao_inscricao,codigo_mesorregiao_inscricao,nota_corte_grupo_preferencia_inscricao,opcoes_cursos_inscricao_inscricao,cnpj_mantenedora_inscricao,codigo_e_mec_mantenedora_inscricao,codigo_e_mec_ies_inscricao,codigo_local_oferta_inscricao,codigo_curso_inscricao,media_nota_enem_inscricao,ano_enem_inscricao,nota_redacao_inscricao,nota_matematica_inscricao,nota_linguagens_inscricao,nota_ciencias_natureza_inscricao,nota_ciencias_humanas_inscricao,percentual_financiamento_inscricao,semestre_financiamento_inscricao,qtde_semestre_financiado_inscricao,CO_CURSO,CO_CINE_AREA_GERAL
count,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,2197234.0,2.197234e+06,1.930434e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197230e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197234e+06,2.197233e+06,2197227.0,2.197233e+06,2.197233e+06,2.197233e+06,2.197233e+06,2.197233e+06,160362.000000,0.0,317462.000000,2.171873e+06,2.171873e+06
mean,2.019778e+03,1.323185e+00,6.989356e+04,1.800095e+02,1.704581e+08,2014.552224,1.923182e+00,2.976886e+03,1.022700e+03,3.038256e+04,3.041455e+03,5.932746e+02,1.688698e+00,2.057784e+13,3.081179e+03,3.167320e+03,6.631268e+05,7.737493e+05,5.489478e+02,2017.278543,6.218451e+02,5.316478e+02,5.341709e+02,5.016815e+02,5.553938e+02,76.085875,NaN,8.721104,7.684461e+05,6.760232e+00
std,7.809612e-01,4.676926e-01,3.033542e+04,2.894536e+02,8.684756e+07,5.289237,1.292683e+00,2.328033e+03,6.459289e+02,1.001842e+04,1.002339e+03,7.886352e+01,7.759046e-01,2.327840e+13,5.075087e+03,4.925744e+03,3.719027e+05,9.615114e+05,6.944929e+01,2.110164,1.496446e+02,1.010469e+02,5.673541e+01,7.288468e+01,7.330013e+01,14.862076,NaN,1.966325,9.643467e+05,2.593773e+00
min,2.019000e+03,1.000000e+00,4.258300e+04,1.000000e+00,1.251817e+07,1961.0,0.000000e+00,0.000000e+00,0.000000e+00,1.100100e+04,1.101000e+03,4.500000e+02,1.000000e+00,5.985700e+10,1.000000e+01,1.000000e+01,2.240000e+02,8.490000e+02,4.362800e+02,2010.0,1.200000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,50.000000,NaN,0.000000,8.490000e+02,1.000000e+00
25%,2.019000e+03,1.000000e+00,4.609600e+04,2.200000e+01,9.753182e+07,2013.0,1.000000e+00,1.449000e+03,5.500000e+02,2.303200e+04,2.307000e+03,5.478200e+02,1.000000e+00,3.950000e+12,3.620000e+02,4.660000e+02,6.578480e+05,6.662700e+04,4.975800e+02,2016.0,5.200000e+02,4.555000e+02,4.977000e+02,4.472000e+02,5.056000e+02,65.400000,NaN,8.000000,6.628800e+04,4.000000e+00
50%,2.020000e+03,1.000000e+00,5.708700e+04,7.000000e+01,2.019994e+08,2016.0,2.000000e+00,2.238000e+03,9.000000e+02,3.103000e+04,3.107000e+03,5.808400e+02,1.000000e+00,7.710000e+12,1.117000e+03,1.502000e+03,6.590960e+05,1.209160e+05,5.336400e+02,2018.0,6.000000e+02,5.178000e+02,5.346000e+02,4.947000e+02,5.585000e+02,80.690000,NaN,10.000000,1.192980e+05,8.000000e+00
75%,2.020000e+03,2.000000e+00,9.114000e+04,2.080000e+02,2.039352e+08,2018.0,3.000000e+00,3.549568e+03,1.286750e+03,3.506100e+04,3.515000e+03,6.206200e+02,2.000000e+00,3.410000e+13,2.415000e+03,3.029000e+03,1.045224e+06,1.303403e+06,5.827000e+02,2019.0,7.200000e+02,5.937000e+02,5.715000e+02,5.479000e+02,6.075000e+02,88.410000,NaN,10.000000,1.300279e+06,9.000000e+00
max,2.021000e+03,2.000000e+00,1.268090e+05,3.014000e+03,3.534557e+08,2021.0,2.900000e+01,5.464642e+04,1.821547e+04,5.300100e+04,5.301000e+03,8.115200e+02,3.000000e+00,9.800000e+13,1.805500e+04,2.455000e+04,2.500004e+06,5.001566e+06,8.190200e+02,2020.0,1.000000e+03,9.920000e+02,8.098000e+02,8.713000e+02,9.062000e+02,98.690000,NaN,16.000000,5.001535e+06,1.000000e+01

==================================================
✅ VALIDAÇÃO DE QUALIDADE CONCLUÍDA
==================================================